In [1]:
import tensorflow as tf

In [3]:
X = tf.random.normal((10000, 20))
X.shape

TensorShape([10000, 20])

In [4]:
y = tf.random.normal((10000, ))
y.shape

TensorShape([10000])

In [7]:
tf.data?

Type:        module
String form: <module 'tensorflow._api.v2.data' from '/Users/baraa/Library/Caches/pypoetry/virtualenvs/transfor <...> rst-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/tensorflow/_api/v2/data/__init__.py'>
File:        ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/tensorflow/_api/v2/data/__init__.py
Docstring:   Public API for tf._api.v2.data namespace

In [8]:
dataset = tf.data.Dataset.from_tensor_slices((X, y))

dataset = (
    dataset
    .shuffle(10000)
    .batch(64)
    .prefetch(tf.data.AUTOTUNE)
)

In [11]:
tf.keras.losses.CategoricalCrossentropy?

Init signature:
tf.keras.losses.CategoricalCrossentropy(
    from_logits=False,
    label_smoothing=0.0,
    axis=-1,
    reduction='sum_over_batch_size',
    name='categorical_crossentropy',
    dtype=None,
)
Docstring:
Computes the crossentropy loss between the labels and predictions.

Use this crossentropy loss function when there are two or more label
classes. We expect labels to be provided in a `one_hot` representation. If
you want to provide labels as integers, please use
`SparseCategoricalCrossentropy` loss. There should be `num_classes` floating
point values per feature, i.e., the shape of both `y_pred` and `y_true` are
`[batch_size, num_classes]`.

Args:
    from_logits: Whether `y_pred` is expected to be a logits tensor. By
        default, we assume that `y_pred` encodes a probability distribution.
    label_smoothing: Float in [0, 1]. When > 0, label values are smoothed,
        meaning the confidence on label values are relaxed. For example, if
        `0.1`, use `0.1 / num_classes` for non-target labels and
        `0.9 + 0.1 / num_classes` for target labels.
    axis: The axis along which to compute crossentropy (the features
        axis). Defaults to `-1`.
    reduction: Type of reduction to apply to the loss. In almost all cases
        this should be `"sum_over_batch_size"`. Supported options are
        `"sum"`, `"sum_over_batch_size"`, `"mean"`,
        `"mean_with_sample_weight"` or `None`. `"sum"` sums the loss,
        `"sum_over_batch_size"` and `"mean"` sum the loss and divide by the
        sample size, and `"mean_with_sample_weight"` sums the loss and
        divides by the sum of the sample weights. `"none"` and `None`
        perform no aggregation. Defaults to `"sum_over_batch_size"`.
    name: Optional name for the loss instance.
    dtype: The dtype of the loss's computations. Defaults to `None`, which
        means using `keras.backend.floatx()`. `keras.backend.floatx()` is a
        `"float32"` unless set to different value
        (via `keras.backend.set_floatx()`). If a `keras.DTypePolicy` is
        provided, then the `compute_dtype` will be utilized.

Examples:

Standalone usage:

>>> y_true = np.array([[0, 1, 0], [0, 0, 1]])
>>> y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])
>>> # Using 'auto'/'sum_over_batch_size' reduction type.
>>> cce = keras.losses.CategoricalCrossentropy()
>>> cce(y_true, y_pred)
1.177

>>> # Calling with 'sample_weight'.
>>> cce(y_true, y_pred, sample_weight=np.array([0.3, 0.7]))
0.814

>>> # Using 'sum' reduction type.
>>> cce = keras.losses.CategoricalCrossentropy(
...     reduction="sum")
>>> cce(y_true, y_pred)
2.354

>>> # Using 'none' reduction type.
>>> cce = keras.losses.CategoricalCrossentropy(
...     reduction=None)
>>> cce(y_true, y_pred)
array([0.0513, 2.303], dtype=float32)

Usage with the `compile()` API:

```python
model.compile(optimizer='sgd',
              loss=keras.losses.CategoricalCrossentropy())
```
File:           ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/keras/src/losses/losses.py
Type:           type
Subclasses:

In [12]:
tf.keras.layers.Dense?

Init signature:
tf.keras.layers.Dense(
    units,
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    lora_rank=None,
    lora_alpha=None,
    quantization_config=None,
    **kwargs,
)
Docstring:
Just your regular densely-connected NN layer.

`Dense` implements the operation:
`output = activation(dot(input, kernel) + bias)`
where `activation` is the element-wise activation function
passed as the `activation` argument, `kernel` is a weights matrix
created by the layer, and `bias` is a bias vector created by the layer
(only applicable if `use_bias` is `True`). When this layer is
followed by a `BatchNormalization` layer, it is recommended to set
`use_bias=False` as `BatchNormalization` has its own bias term.

Note: If the input to the layer has a rank greater than 2, `Dense`
computes the dot product between the `inputs` and the `kernel` along the
last axis of the `inputs` and axis 0 of the `kernel` (using `tf.tensordot`).
For example, if input has dimensions `(batch_size, d0, d1)`, then we create
a `kernel` with shape `(d1, units)`, and the `kernel` operates along axis 2
of the `input`, on every sub-tensor of shape `(1, 1, d1)` (there are
`batch_size * d0` such sub-tensors). The output in this case will have
shape `(batch_size, d0, units)`.

Args:
    units: Positive integer, dimensionality of the output space.
    activation: Activation function to use.
        If you don't specify anything, no activation is applied
        (ie. "linear" activation: `a(x) = x`).
    use_bias: Boolean, whether the layer uses a bias vector.
    kernel_initializer: Initializer for the `kernel` weights matrix.
    bias_initializer: Initializer for the bias vector.
    kernel_regularizer: Regularizer function applied to
        the `kernel` weights matrix.
    bias_regularizer: Regularizer function applied to the bias vector.
    activity_regularizer: Regularizer function applied to
        the output of the layer (its "activation").
    kernel_constraint: Constraint function applied to
        the `kernel` weights matrix.
    bias_constraint: Constraint function applied to the bias vector.
    lora_rank: Optional integer. If set, the layer's forward pass
        will implement LoRA (Low-Rank Adaptation)
        with the provided rank. LoRA sets the layer's kernel
        to non-trainable and replaces it with a delta over the
        original kernel, obtained via multiplying two lower-rank
        trainable matrices. This can be useful to reduce the
        computation cost of fine-tuning large dense layers.
        You can also enable LoRA on an existing
        `Dense` layer by calling `layer.enable_lora(rank)`.
    lora_alpha: Optional integer. If set, this parameter scales the
        low-rank adaptation delta (computed as the product of two lower-rank
        trainable matrices) during the forward pass. The delta is scaled by
        `lora_alpha / lora_rank`, allowing you to fine-tune the strength of
        the LoRA adjustment independently of `lora_rank`.

Input shape:
    N-D tensor with shape: `(batch_size, ..., input_dim)`.
    The most common situation would be
    a 2D input with shape `(batch_size, input_dim)`.

Output shape:
    N-D tensor with shape: `(batch_size, ..., units)`.
    For instance, for a 2D input with shape `(batch_size, input_dim)`,
    the output would have shape `(batch_size, units)`.
File:           ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/keras/src/layers/core/dense.py
Type:           type
Subclasses:

In [14]:
model = tf.keras.Sequential([tf.keras.Input((12,)),
                             tf.keras.layers.Dense(32, activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(16, activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(1),
                            ])

In [15]:
tf.keras.losses.BinaryCrossentropy?

Init signature:
tf.keras.losses.BinaryCrossentropy(
    from_logits=False,
    label_smoothing=0.0,
    axis=-1,
    reduction='sum_over_batch_size',
    name='binary_crossentropy',
    dtype=None,
)
Docstring:
Computes the cross-entropy loss between true labels and predicted labels.

Use this cross-entropy loss for binary (0 or 1) classification applications.
The loss function requires the following inputs:

- `y_true` (true label): This is either 0 or 1.
- `y_pred` (predicted value): This is the model's prediction, i.e, a single
    floating-point value which either represents a
    [logit](https://en.wikipedia.org/wiki/Logit), (i.e, value in [-inf, inf]
    when `from_logits=True`) or a probability (i.e, value in [0., 1.] when
    `from_logits=False`).

Args:
    from_logits: Whether to interpret `y_pred` as a tensor of
        [logit](https://en.wikipedia.org/wiki/Logit) values. By default, we
        assume that `y_pred` is probabilities (i.e., values in [0, 1]).
    label_smoothing: Float in range [0, 1]. When 0, no smoothing occurs.
        When > 0, we compute the loss between the predicted labels
        and a smoothed version of the true labels, where the smoothing
        squeezes the labels towards 0.5. Larger values of
        `label_smoothing` correspond to heavier smoothing.
    axis: The axis along which to compute crossentropy (the features axis).
        Defaults to `-1`.
    reduction: Type of reduction to apply to the loss. In almost all cases
        this should be `"sum_over_batch_size"`. Supported options are
        `"sum"`, `"sum_over_batch_size"`, `"mean"`,
        `"mean_with_sample_weight"` or `None`. `"sum"` sums the loss,
        `"sum_over_batch_size"` and `"mean"` sum the loss and divide by the
        sample size, and `"mean_with_sample_weight"` sums the loss and
        divides by the sum of the sample weights. `"none"` and `None`
        perform no aggregation. Defaults to `"sum_over_batch_size"`.
    name: Optional name for the loss instance.
    dtype: The dtype of the loss's computations. Defaults to `None`, which
        means using `keras.backend.floatx()`. `keras.backend.floatx()` is a
        `"float32"` unless set to different value
        (via `keras.backend.set_floatx()`). If a `keras.DTypePolicy` is
        provided, then the `compute_dtype` will be utilized.

Examples:

**Recommended Usage:** (set `from_logits=True`)

With `compile()` API:

```python
model.compile(
    loss=keras.losses.BinaryCrossentropy(from_logits=True),
    ...
)
```

As a standalone function:

>>> # Example 1: (batch_size = 1, number of samples = 4)
>>> y_true = np.array([0, 1, 0, 0])
>>> y_pred = np.array([-18.6, 0.51, 2.94, -12.8])
>>> bce = keras.losses.BinaryCrossentropy(from_logits=True)
>>> bce(y_true, y_pred)
0.8654

>>> # Example 2: (batch_size = 2, number of samples = 4)
>>> y_true = np.array([[0, 1], [0, 0]])
>>> y_pred = np.array([[-18.6, 0.51], [2.94, -12.8]])
>>> # Using default 'auto'/'sum_over_batch_size' reduction type.
>>> bce = keras.losses.BinaryCrossentropy(from_logits=True)
>>> bce(y_true, y_pred)
0.8654
>>> # Using 'sample_weight' attribute
>>> bce(y_true, y_pred, sample_weight=[0.8, 0.2])
0.243
>>> # Using 'sum' reduction` type.
>>> bce = keras.losses.BinaryCrossentropy(from_logits=True,
...     reduction="sum")
>>> bce(y_true, y_pred)
1.730
>>> # Using 'none' reduction type.
>>> bce = keras.losses.BinaryCrossentropy(from_logits=True,
...     reduction=None)
>>> bce(y_true, y_pred)
array([0.235, 1.496], dtype=float32)

**Default Usage:** (set `from_logits=False`)

>>> # Make the following updates to the above "Recommended Usage" section
>>> # 1. Set `from_logits=False`
>>> keras.losses.BinaryCrossentropy() # OR ...('from_logits=False')
>>> # 2. Update `y_pred` to use probabilities instead of logits
>>> y_pred = [0.6, 0.3, 0.2, 0.8] # OR [[0.6, 0.3], [0.2, 0.8]]
File:           ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/keras/src/losses/losses.py
Type:           type
Subclasses:

In [16]:
tf.keras.optimizers.Adam?

Init signature:
tf.keras.optimizers.Adam(
    learning_rate=0.001,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07,
    amsgrad=False,
    weight_decay=None,
    clipnorm=None,
    clipvalue=None,
    global_clipnorm=None,
    use_ema=False,
    ema_momentum=0.99,
    ema_overwrite_frequency=None,
    loss_scale_factor=None,
    gradient_accumulation_steps=None,
    name=None,
    **kwargs,
)
Docstring:
Optimizer that implements the Adam algorithm.

Adam optimization is a stochastic gradient descent method that is based on
adaptive estimation of first-order and second-order moments.

According to
[Kingma et al., 2014](http://arxiv.org/abs/1412.6980),
the method is "*computationally
efficient, has little memory requirement, invariant to diagonal rescaling of
gradients, and is well suited for problems that are large in terms of
data/parameters*".

Args:
    learning_rate: A float, a
        `keras.optimizers.schedules.LearningRateSchedule` instance, or
        a callable that takes no arguments and returns the actual value to
        use. The learning rate. Defaults to `0.001`.
    beta_1: A float value or a constant float tensor, or a callable
        that takes no arguments and returns the actual value to use. The
        exponential decay rate for the 1st moment estimates. Defaults to
        `0.9`.
    beta_2: A float value or a constant float tensor, or a callable
        that takes no arguments and returns the actual value to use. The
        exponential decay rate for the 2nd moment estimates. Defaults to
        `0.999`.
    epsilon: A small constant for numerical stability. This epsilon is
        "epsilon hat" in the Kingma and Ba paper (in the formula just before
        Section 2.1), not the epsilon in Algorithm 1 of the paper. Defaults
        to `1e-7`.
    amsgrad: Boolean. Whether to apply AMSGrad variant of this algorithm
        from the paper "On the Convergence of Adam and beyond". Defaults
        to `False`.
    name: String. The name to use
        for momentum accumulator weights created by
        the optimizer.
    weight_decay: Float. If set, weight decay is applied.
    clipnorm: Float. If set, the gradient of each weight is individually
        clipped so that its norm is no higher than this value.
    clipvalue: Float. If set, the gradient of each weight is clipped to be
        no higher than this value.
    global_clipnorm: Float. If set, the gradient of all weights is clipped
        so that their global norm is no higher than this value.
    use_ema: Boolean, defaults to `False`.
        If `True`, exponential moving average
        (EMA) is applied. EMA consists of computing an exponential moving
        average of the weights of the model (as the weight values change
        after each training batch), and periodically overwriting the
        weights with their moving average.
    ema_momentum: Float, defaults to 0.99. Only used if `use_ema=True`.
        This is the momentum to use when computing
        the EMA of the model's weights:
        `new_average = ema_momentum * old_average + (1 - ema_momentum) *
        current_variable_value`.
    ema_overwrite_frequency: Int or None, defaults to None. Only used if
        `use_ema=True`. Every `ema_overwrite_frequency` steps of iterations,
        we overwrite the model variable by its moving average.
        If None, the optimizer
        does not overwrite model variables in the middle of training,
        and you need to explicitly overwrite the variables
        at the end of training by calling
        `optimizer.finalize_variable_values()` (which updates the model
        variables in-place). When using the built-in `fit()` training loop,
        this happens automatically after the last epoch,
        and you don't need to do anything.
    loss_scale_factor: Float or `None`. If a float, the scale factor will
        be multiplied the loss before computing gradients, and the inverse
        of the scale factor will be multiplied by the gradients before
        updating variables. Useful for preventing underflow during
        mixed precision training. Alternately,
        `keras.optimizers.LossScaleOptimizer` will
        automatically set a loss scale factor.
    gradient_accumulation_steps: Int or `None`. If an int, model & optimizer
        variables will not be updated at every step; instead they will be
        updated every `gradient_accumulation_steps` steps, using the average
        value of the gradients since the last update. This is known as
        "gradient accumulation". This can be useful
        when your batch size is very small, in order to reduce gradient
        noise at each update step. EMA frequency will look at "accumulated"
        iterations value (optimizer steps // gradient_accumulation_steps).
        Learning rate schedules will look at "real" iterations value
        (optimizer steps).
File:           ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/keras/src/optimizers/adam.py
Type:           type
Subclasses:     AdamW

In [18]:
loss_fn = tf.keras.losses.BinaryCrossentropy(from_logits=True)
optim = tf.keras.optimizers.Adam(learning_rate=1e-3)

In [ ]:
with tf.GradientTape() as tape:
    pred = model(x, training=True)
    loss = loss_fn(y, pred)

grads = tape.gradient(loss, model.trainable_variables)
optimizer.apply_gradients(zip(grads, model.trainable_variables))

loss_metric.update_state(loss)

In [20]:
loss_fn?

Signature:   loss_fn(y_true, y_pred, sample_weight=None)
Type:        BinaryCrossentropy
String form: <LossFunctionWrapper(<function binary_crossentropy at 0x117977100>, kwargs={'from_logits': True, 'label_smoothing': 0.0, 'axis': -1})>
File:        ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/keras/src/losses/losses.py
Docstring:
Computes the cross-entropy loss between true labels and predicted labels.

Use this cross-entropy loss for binary (0 or 1) classification applications.
The loss function requires the following inputs:

- `y_true` (true label): This is either 0 or 1.
- `y_pred` (predicted value): This is the model's prediction, i.e, a single
    floating-point value which either represents a
    [logit](https://en.wikipedia.org/wiki/Logit), (i.e, value in [-inf, inf]
    when `from_logits=True`) or a probability (i.e, value in [0., 1.] when
    `from_logits=False`).

Args:
    from_logits: Whether to interpret `y_pred` as a tensor of
        [logit](https://en.wikipedia.org/wiki/Logit) values. By default, we
        assume that `y_pred` is probabilities (i.e., values in [0, 1]).
    label_smoothing: Float in range [0, 1]. When 0, no smoothing occurs.
        When > 0, we compute the loss between the predicted labels
        and a smoothed version of the true labels, where the smoothing
        squeezes the labels towards 0.5. Larger values of
        `label_smoothing` correspond to heavier smoothing.
    axis: The axis along which to compute crossentropy (the features axis).
        Defaults to `-1`.
    reduction: Type of reduction to apply to the loss. In almost all cases
        this should be `"sum_over_batch_size"`. Supported options are
        `"sum"`, `"sum_over_batch_size"`, `"mean"`,
        `"mean_with_sample_weight"` or `None`. `"sum"` sums the loss,
        `"sum_over_batch_size"` and `"mean"` sum the loss and divide by the
        sample size, and `"mean_with_sample_weight"` sums the loss and
        divides by the sum of the sample weights. `"none"` and `None`
        perform no aggregation. Defaults to `"sum_over_batch_size"`.
    name: Optional name for the loss instance.
    dtype: The dtype of the loss's computations. Defaults to `None`, which
        means using `keras.backend.floatx()`. `keras.backend.floatx()` is a
        `"float32"` unless set to different value
        (via `keras.backend.set_floatx()`). If a `keras.DTypePolicy` is
        provided, then the `compute_dtype` will be utilized.

Examples:

**Recommended Usage:** (set `from_logits=True`)

With `compile()` API:

```python
model.compile(
    loss=keras.losses.BinaryCrossentropy(from_logits=True),
    ...
)
```

As a standalone function:

>>> # Example 1: (batch_size = 1, number of samples = 4)
>>> y_true = np.array([0, 1, 0, 0])
>>> y_pred = np.array([-18.6, 0.51, 2.94, -12.8])
>>> bce = keras.losses.BinaryCrossentropy(from_logits=True)
>>> bce(y_true, y_pred)
0.8654

>>> # Example 2: (batch_size = 2, number of samples = 4)
>>> y_true = np.array([[0, 1], [0, 0]])
>>> y_pred = np.array([[-18.6, 0.51], [2.94, -12.8]])
>>> # Using default 'auto'/'sum_over_batch_size' reduction type.
>>> bce = keras.losses.BinaryCrossentropy(from_logits=True)
>>> bce(y_true, y_pred)
0.8654
>>> # Using 'sample_weight' attribute
>>> bce(y_true, y_pred, sample_weight=[0.8, 0.2])
0.243
>>> # Using 'sum' reduction` type.
>>> bce = keras.losses.BinaryCrossentropy(from_logits=True,
...     reduction="sum")
>>> bce(y_true, y_pred)
1.730
>>> # Using 'none' reduction type.
>>> bce = keras.losses.BinaryCrossentropy(from_logits=True,
...     reduction=None)
>>> bce(y_true, y_pred)
array([0.235, 1.496], dtype=float32)

**Default Usage:** (set `from_logits=False`)

>>> # Make the following updates to the above "Recommended Usage" section
>>> # 1. Set `from_logits=False`
>>> keras.losses.BinaryCrossentropy() # OR ...('from_logits=False')
>>> # 2. Update `y_pred` to use probabilities instead of logits
>>> y_pred = [0.6, 0.3, 0.2, 0.8] # OR [[0.6, 0.3], [0.2, 0.8]]

In [ ]:
with tf.GradientTape() as tape:
    pred = model(x, training=True)
    loss = loss_fn(y, pred)

grads = tape.gradient(loss, model.trainable_variables)
optimizer.apply_gradients(zip(grads, model.trainable_variables))

loss_metric.update_state(loss)

In [ ]:
with tf.GradientTape() as tape:
    pred = model(x, training=True)
    loss = loss_fn(y, pred)

grads = tape.gradient(loss, model.trainable_variables)
optim.apply_gradients(zip(grads, model.trainable_variables))

loss

In [21]:
tf.data.Dataset?

Init signature: tf.data.Dataset(variant_tensor)
Docstring:
Represents a potentially large set of elements.

The `tf.data.Dataset` API supports writing descriptive and efficient input
pipelines. `Dataset` usage follows a common pattern:

1. Create a source dataset from your input data.
2. Apply dataset transformations to preprocess the data.
3. Iterate over the dataset and process the elements.

Iteration happens in a streaming fashion, so the full dataset does not need to
fit into memory.

Source Datasets:

The simplest way to create a dataset is to create it from a python `list`:

>>> dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
>>> for element in dataset:
...   print(element)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)

To process lines from files, use `tf.data.TextLineDataset`:

>>> dataset = tf.data.TextLineDataset(["file1.txt", "file2.txt"])

To process records written in the `TFRecord` format, use `TFRecordDataset`:

>>> dataset = tf.data.TFRecordDataset(["file1.tfrecords", "file2.tfrecords"])

To create a dataset of all files matching a pattern, use
`tf.data.Dataset.list_files`:

```python
dataset = tf.data.Dataset.list_files("/path/*.txt")
```

See `tf.data.FixedLengthRecordDataset` and `tf.data.Dataset.from_generator`
for more ways to create datasets.

Transformations:

Once you have a dataset, you can apply transformations to prepare the data for
your model:

>>> dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
>>> dataset = dataset.map(lambda x: x*2)
>>> [a.item() for a in dataset.as_numpy_iterator()]
[2, 4, 6]

Common Terms:

**Element**: A single output from calling `next()` on a dataset iterator.
  Elements may be nested structures containing multiple components. For
  example, the element `(1, (3, "apple"))` has one tuple nested in another
  tuple. The components are `1`, `3`, and `"apple"`.

**Component**: The leaf in the nested structure of an element.

Supported types:

Elements can be nested structures of tuples, named tuples, and dictionaries.
Note that Python lists are *not* treated as nested structures of components.
Instead, lists are converted to tensors and treated as components. For
example, the element `(1, [1, 2, 3])` has only two components; the tensor `1`
and the tensor `[1, 2, 3]`. Element components can be of any type
representable by `tf.TypeSpec`, including `tf.Tensor`, `tf.data.Dataset`,
`tf.sparse.SparseTensor`, `tf.RaggedTensor`, and `tf.TensorArray`.

```python
a = 1 # Integer element
b = 2.0 # Float element
c = (1, 2) # Tuple element with 2 components
d = {"a": (2, 2), "b": 3} # Dict element with 3 components
Point = collections.namedtuple("Point", ["x", "y"])
e = Point(1, 2) # Named tuple
f = tf.data.Dataset.range(10) # Dataset element
```

For more information,
read [this guide](https://www.tensorflow.org/guide/data).
Init docstring:
Creates a DatasetV2 object.

This is a difference between DatasetV1 and DatasetV2. DatasetV1 does not
take anything in its constructor whereas in the DatasetV2, we expect
subclasses to create a variant_tensor and pass it in to the super() call.

Args:
  variant_tensor: A DT_VARIANT tensor that represents the dataset.
File:           ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/tensorflow/python/data/ops/dataset_ops.py
Type:           ABCMeta
Subclasses:     DatasetV1, DatasetSource, UnaryDataset, _VariantDataset, TFRecordDatasetV2, _PerDeviceGenerator, _ReincarnatedPerDeviceGenerator

In [90]:
x = tf.random.normal((64, 20))
W = tf.random.normal((20, 32))
b = tf.random.normal((32,))

y = tf.matmul(x, W) + b

In [26]:
x[0,0].numpy()

np.float32(-1.6457713)

In [109]:
model = tf.keras.Sequential([tf.keras.Input((20,)),
                             tf.keras.layers.Dense(64, activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(1),
                            ])

In [110]:
loss_fun = tf.keras.losses.BinaryCrossentropy(from_logits=True)

In [111]:
x.shape

TensorShape([20, 10])

In [114]:
pred = model(tf.transpose(x))
pred.shape

TensorShape([10, 1])

In [92]:
probs = tf.sigmoid(pred)

In [93]:
loss = loss_fn(true, probs)

In [94]:
loss

In [44]:
tf.data.Dataset?

Init signature: tf.data.Dataset(variant_tensor)
Docstring:
Represents a potentially large set of elements.

The `tf.data.Dataset` API supports writing descriptive and efficient input
pipelines. `Dataset` usage follows a common pattern:

1. Create a source dataset from your input data.
2. Apply dataset transformations to preprocess the data.
3. Iterate over the dataset and process the elements.

Iteration happens in a streaming fashion, so the full dataset does not need to
fit into memory.

Source Datasets:

The simplest way to create a dataset is to create it from a python `list`:

>>> dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
>>> for element in dataset:
...   print(element)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)

To process lines from files, use `tf.data.TextLineDataset`:

>>> dataset = tf.data.TextLineDataset(["file1.txt", "file2.txt"])

To process records written in the `TFRecord` format, use `TFRecordDataset`:

>>> dataset = tf.data.TFRecordDataset(["file1.tfrecords", "file2.tfrecords"])

To create a dataset of all files matching a pattern, use
`tf.data.Dataset.list_files`:

```python
dataset = tf.data.Dataset.list_files("/path/*.txt")
```

See `tf.data.FixedLengthRecordDataset` and `tf.data.Dataset.from_generator`
for more ways to create datasets.

Transformations:

Once you have a dataset, you can apply transformations to prepare the data for
your model:

>>> dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
>>> dataset = dataset.map(lambda x: x*2)
>>> [a.item() for a in dataset.as_numpy_iterator()]
[2, 4, 6]

Common Terms:

**Element**: A single output from calling `next()` on a dataset iterator.
  Elements may be nested structures containing multiple components. For
  example, the element `(1, (3, "apple"))` has one tuple nested in another
  tuple. The components are `1`, `3`, and `"apple"`.

**Component**: The leaf in the nested structure of an element.

Supported types:

Elements can be nested structures of tuples, named tuples, and dictionaries.
Note that Python lists are *not* treated as nested structures of components.
Instead, lists are converted to tensors and treated as components. For
example, the element `(1, [1, 2, 3])` has only two components; the tensor `1`
and the tensor `[1, 2, 3]`. Element components can be of any type
representable by `tf.TypeSpec`, including `tf.Tensor`, `tf.data.Dataset`,
`tf.sparse.SparseTensor`, `tf.RaggedTensor`, and `tf.TensorArray`.

```python
a = 1 # Integer element
b = 2.0 # Float element
c = (1, 2) # Tuple element with 2 components
d = {"a": (2, 2), "b": 3} # Dict element with 3 components
Point = collections.namedtuple("Point", ["x", "y"])
e = Point(1, 2) # Named tuple
f = tf.data.Dataset.range(10) # Dataset element
```

For more information,
read [this guide](https://www.tensorflow.org/guide/data).
Init docstring:
Creates a DatasetV2 object.

This is a difference between DatasetV1 and DatasetV2. DatasetV1 does not
take anything in its constructor whereas in the DatasetV2, we expect
subclasses to create a variant_tensor and pass it in to the super() call.

Args:
  variant_tensor: A DT_VARIANT tensor that represents the dataset.
File:           ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/tensorflow/python/data/ops/dataset_ops.py
Type:           ABCMeta
Subclasses:     DatasetV1, DatasetSource, UnaryDataset, _VariantDataset, TFRecordDatasetV2, _PerDeviceGenerator, _ReincarnatedPerDeviceGenerator

In [45]:
import numpy as np

In [85]:
X_train_np = np.random.randn(20, 10)
y_train_np = np.random.randint(0, 2, 20)

In [50]:
tf.data.Dataset?

Init signature: tf.data.Dataset(variant_tensor)
Docstring:
Represents a potentially large set of elements.

The `tf.data.Dataset` API supports writing descriptive and efficient input
pipelines. `Dataset` usage follows a common pattern:

1. Create a source dataset from your input data.
2. Apply dataset transformations to preprocess the data.
3. Iterate over the dataset and process the elements.

Iteration happens in a streaming fashion, so the full dataset does not need to
fit into memory.

Source Datasets:

The simplest way to create a dataset is to create it from a python `list`:

>>> dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
>>> for element in dataset:
...   print(element)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)

To process lines from files, use `tf.data.TextLineDataset`:

>>> dataset = tf.data.TextLineDataset(["file1.txt", "file2.txt"])

To process records written in the `TFRecord` format, use `TFRecordDataset`:

>>> dataset = tf.data.TFRecordDataset(["file1.tfrecords", "file2.tfrecords"])

To create a dataset of all files matching a pattern, use
`tf.data.Dataset.list_files`:

```python
dataset = tf.data.Dataset.list_files("/path/*.txt")
```

See `tf.data.FixedLengthRecordDataset` and `tf.data.Dataset.from_generator`
for more ways to create datasets.

Transformations:

Once you have a dataset, you can apply transformations to prepare the data for
your model:

>>> dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
>>> dataset = dataset.map(lambda x: x*2)
>>> [a.item() for a in dataset.as_numpy_iterator()]
[2, 4, 6]

Common Terms:

**Element**: A single output from calling `next()` on a dataset iterator.
  Elements may be nested structures containing multiple components. For
  example, the element `(1, (3, "apple"))` has one tuple nested in another
  tuple. The components are `1`, `3`, and `"apple"`.

**Component**: The leaf in the nested structure of an element.

Supported types:

Elements can be nested structures of tuples, named tuples, and dictionaries.
Note that Python lists are *not* treated as nested structures of components.
Instead, lists are converted to tensors and treated as components. For
example, the element `(1, [1, 2, 3])` has only two components; the tensor `1`
and the tensor `[1, 2, 3]`. Element components can be of any type
representable by `tf.TypeSpec`, including `tf.Tensor`, `tf.data.Dataset`,
`tf.sparse.SparseTensor`, `tf.RaggedTensor`, and `tf.TensorArray`.

```python
a = 1 # Integer element
b = 2.0 # Float element
c = (1, 2) # Tuple element with 2 components
d = {"a": (2, 2), "b": 3} # Dict element with 3 components
Point = collections.namedtuple("Point", ["x", "y"])
e = Point(1, 2) # Named tuple
f = tf.data.Dataset.range(10) # Dataset element
```

For more information,
read [this guide](https://www.tensorflow.org/guide/data).
Init docstring:
Creates a DatasetV2 object.

This is a difference between DatasetV1 and DatasetV2. DatasetV1 does not
take anything in its constructor whereas in the DatasetV2, we expect
subclasses to create a variant_tensor and pass it in to the super() call.

Args:
  variant_tensor: A DT_VARIANT tensor that represents the dataset.
File:           ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/tensorflow/python/data/ops/dataset_ops.py
Type:           ABCMeta
Subclasses:     DatasetV1, DatasetSource, UnaryDataset, _VariantDataset, TFRecordDatasetV2, _PerDeviceGenerator, _ReincarnatedPerDeviceGenerator

In [86]:
train_ds = (
    tf.data.Dataset
    .from_tensor_slices((X_train_np, y_train_np))
    #.batch(64)
    .shuffle(5000)
    .batch(64)
    .prefetch(tf.data.AUTOTUNE)
)

In [104]:
for x, y in train_ds:
    print(x.shape)
    print(y.shape)
    break

(20, 10)
(20,)

In [67]:
len(train_ds)

157

In [68]:
157 * 64

10048

In [59]:
len(x)

64

In [70]:
x[0]

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([ 2.21636488, -0.21331002,  1.06265208,  0.3880169 , -0.2543586 ,
        1.42131514,  0.87254039, -0.23810739,  0.11892428,  0.16837715])>

In [71]:
for x, y in train_ds:
    print(x[0])

tf.Tensor(
[-0.43342139 -0.87267128 -1.12944645  1.46129167 -1.82480735  0.62231112
 -0.72851951  0.81217538 -1.10540682  0.81985678], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.08901353  0.01574402 -0.44578584  2.3205371   1.47306466 -0.58716013
  0.26780295  0.26443316  0.27008965 -1.24627488], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.29739471 -0.11964834 -0.45570712 -0.03752417  0.24645751  0.4751765
 -0.0154233  -0.72893509 -0.27170226 -0.1713642 ], shape=(10,), dtype=float64)
tf.Tensor(
[-0.34129677  0.26467385  0.38638191 -0.72218305  1.14053148 -0.47868774
 -0.84608171  1.67049453 -1.05600865 -0.29564646], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.15293037  2.58077391  1.03771345  1.20395452 -0.28739784 -0.17711241
 -0.39749019  0.0259135   0.94861691 -0.59672827], shape=(10,), dtype=float64)
tf.Tensor(
[-0.41165814 -0.89980667 -1.77447904 -0.35259124 -0.13515269  1.27480039
 -0.85381739 -0.75362219  1.57992603  1.56499738], shape=(10,), dtype=float64)
tf.Tensor(
[-0.81210409 -0.4501133  -0.99483328  1.41464598 -0.87906831  0.42551311
 -0.47177018 -0.31017445  1.79124851  0.41429905], shape=(10,), dtype=float64)
tf.Tensor(
[-0.29732013 -0.0493898   1.18264439 -0.35814159 -0.29768368 -0.10271997
 -0.68285362  0.04370525 -0.25627142 -1.36986598], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.34492407  0.39798496 -0.62245955 -1.04043561  0.13927366  0.16517942
 -0.06194274 -0.29136583  0.40442718  0.52622184], shape=(10,), dtype=float64)
tf.Tensor(
[-0.99880611 -1.70468732  1.4411214  -0.55598459 -1.67532924 -0.72507379
  1.63364682 -0.1921756   0.58980693 -0.80086638], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.81033706 -2.14185572  0.30382784 -0.59112451 -0.82606379 -0.25163672
 -0.24586006  0.65341965  1.00762986  0.17234158], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.02085128 -1.01499416  0.5906979   0.11449668 -1.25353604 -1.45757181
 -0.17350326  1.20287885  1.39654288 -4.10068731], shape=(10,), dtype=float64)
tf.Tensor(
[-1.4989722  -0.09213462 -1.63357154  0.73636272 -0.6413198   1.63069729
 -0.76978042 -0.08089326 -2.00518256 -0.55671908], shape=(10,), dtype=float64)
tf.Tensor(
[-0.08143622  1.1244586   0.60043906  0.05217238 -1.01360605  1.12698915
 -0.25617902  0.11107561  0.00914002 -0.52010688], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.78057145  0.40043973 -0.20992594 -0.34856559 -0.04066175 -1.33299008
 -2.42506516 -0.98042967  0.042662    0.30765692], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.16931831 -0.12203716 -0.79087954  0.15254364  0.00209263  0.38969151
  0.28777211  0.28019072  0.72699002 -1.00017221], shape=(10,), dtype=float64)
tf.Tensor(
[-1.54528019 -0.3774268  -0.23543965  0.2368231  -0.3393678  -0.6747138
 -0.75145896  0.87002114 -1.95578604 -1.22424615], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.48980868  0.33956584  1.56920925  1.27372197 -0.71241776  0.60598249
  1.11807793 -0.15810691  1.25775128 -0.25583644], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.22297575  1.43997629  0.63601598 -1.11356995  1.00327949 -0.12037967
 -0.14855335  0.47731773 -0.48673135 -0.71495995], shape=(10,), dtype=float64)
tf.Tensor(
[-0.64940959  0.31189376 -1.67978154  0.21334651  0.90530592  0.49695598
 -0.27489419 -0.75665203  1.02868558  0.346712  ], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.62035407  0.9093679   0.31166671  0.67114914  0.65547132 -1.25500315
  0.00926433 -0.04920582  0.1147774   1.31329702], shape=(10,), dtype=float64)
tf.Tensor(
[-0.51802316  0.12227033 -0.6874594  -2.55459986  1.57095753 -0.02944871
 -0.8566198  -1.22045104  0.27708278 -1.26402727], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.26242391  0.13594647  0.00280698 -0.02301686  1.63395385 -0.54432535
 -0.53683575  0.89167029  1.10446713  1.13942004], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.05457965 -0.23220444 -0.84181169  0.64694065  0.65403897  1.14446379
  0.92900029 -0.18017438  0.34760366 -0.13240263], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.93731788  0.40403579 -0.79075467  1.37917074 -0.02267208 -0.4462902
 -0.50643453  0.47778279  0.94133072  0.99673314], shape=(10,), dtype=float64)
tf.Tensor(
[-1.97378998  0.51384854 -1.53963113 -0.12164894 -0.70744128  0.26312632
  0.22286388  0.07249765 -0.54403123  0.64705258], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.59697094  0.85827085  0.77584442  0.37619739  1.42964177 -0.28305236
  1.20227922 -0.77077614 -0.97536371  0.40774912], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.04196564 -0.21159    -1.59259926 -0.94006281 -1.16483913 -0.92336676
 -0.05879412  0.27673925  0.74711457 -1.81778358], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.15194884  0.83672736 -0.93822735 -0.2922707   0.15263861 -0.44988791
  0.26499484  0.56703097 -0.76749534 -1.57178187], shape=(10,), dtype=float64)
tf.Tensor(
[-0.07081565  0.23371362 -0.52207117  0.40271856  0.53375071  0.19914119
 -0.68396153  0.80650086  1.0881299   0.89808835], shape=(10,), dtype=float64)
tf.Tensor(
[-0.82098903 -0.33329573 -1.38970164  0.5302129  -0.06821183 -0.93153268
  0.27499492 -1.08647194  0.60751769 -1.11109729], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.64549079  0.38489192 -1.06763671  0.40901348  0.87664568 -1.07973904
  0.0359956  -1.28184544 -0.08581621 -0.32988102], shape=(10,), dtype=float64)
tf.Tensor(
[ 2.34750878  1.19317609 -0.9123966  -0.33714034  0.87138445  0.50036817
  1.25256445  0.13344995  2.06452915 -0.68480624], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.21684236  0.18871883 -1.06473565 -0.94951831 -0.02397081 -0.50075153
  2.28534933 -0.2904941   0.36798638 -1.44281255], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.48735083  0.57828777  0.57497464  0.08405491  0.80119295  0.53661967
 -0.32063996  0.05286987  0.16115226  0.35257935], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.59038788  1.0558365   1.44423131  0.73494704  1.55348881  1.26116623
  0.94221115  1.30090836  0.62889721 -0.26065305], shape=(10,), dtype=float64)
tf.Tensor(
[-0.64914848 -0.2952985   0.85374985  0.62633913  0.86448269  1.69207777
  0.10506519  0.5721309   1.79794704  1.16952257], shape=(10,), dtype=float64)
tf.Tensor(
[-1.1297613  -0.21708799  1.05799058 -1.09251922  1.03211873 -0.07936351
  2.14087283  1.24275413 -1.12182777  0.08166646], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.151695    0.60129162 -0.34720207 -0.46536034  0.32894409  0.95685719
  2.16411422  0.47009138  1.24666573  0.91528255], shape=(10,), dtype=float64)
tf.Tensor(
[-5.19969540e-01  9.52598934e-01 -8.61878914e-01  1.17272897e+00
  1.13824949e-03  3.50993640e-01 -6.91343657e-01 -7.32053139e-01
  1.04181982e+00 -6.61857006e-01], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.43744163 -0.43557449 -1.80647046  0.24493881 -1.23105687  0.50257786
  0.507332    1.61021471  0.60970535 -1.01277036], shape=(10,), dtype=float64)
tf.Tensor(
[-0.46161798 -1.10432328 -1.417809   -0.97596891 -1.14762147 -1.5066117
  1.60382479 -0.03567148  0.35977392 -0.75223119], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.97776972  0.19923663  0.38419173  2.4435139  -0.4007304   0.24680604
  0.18399399 -0.15931313  0.54053456  0.15559837], shape=(10,), dtype=float64)
tf.Tensor(
[-2.25236937  0.21024573 -0.28292711 -0.37068773  1.65374557  1.02649072
 -0.23696031 -1.69370336 -0.23575619 -0.28072164], shape=(10,), dtype=float64)
tf.Tensor(
[-0.97175517 -0.66914997 -0.70181668  1.07342373  0.41771132 -0.48560301
 -0.95177025  0.95606153  1.04632965 -0.84447003], shape=(10,), dtype=float64)
tf.Tensor(
[-0.53760427 -0.17261981 -1.64478328 -0.27449425  0.22889096  0.39856365
 -1.64529406  0.42391827  0.22591192  2.28425346], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.39938304  0.47131189  0.04491849  0.74527229  1.35651741  0.91407522
  0.3132274   1.06878411 -0.38290874  0.15433621], shape=(10,), dtype=float64)
tf.Tensor(
[-0.39749139 -1.72674616 -1.05951255  0.44662276 -2.06948753  0.33056494
 -0.70896018  0.36058679  0.49806632 -0.69918917], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.69265503  1.32446017  0.14952768 -0.21139684  0.86394549  0.81840094
 -0.03045759 -1.71889467 -0.07364159  1.57690716], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.24428414  0.92526094 -1.02048056 -0.45305153  0.7028634  -1.0631857
 -2.26538234  0.47534088  1.28808756  0.83514744], shape=(10,), dtype=float64)
tf.Tensor(
[-1.23001677  0.33203247  0.40817255 -0.47212676 -0.1140857  -0.8186504
  0.16254436  0.10853481  1.37511637  1.35930196], shape=(10,), dtype=float64)
tf.Tensor(
[-1.16098224  0.35860147 -0.82846458 -0.13543295  1.4819701   1.43429123
  0.78388002  0.11929649 -0.17322495  0.7481151 ], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.03756826 -0.3282954  -1.57797283 -1.12607328  0.17241929 -0.62841847
 -2.22397328 -0.73936374 -0.58273215 -2.36339017], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.06130171 -0.45745707  1.01119124  0.66494052  1.2368183  -0.91732247
  1.09493912  0.55052929 -0.55529258  0.21218101], shape=(10,), dtype=float64)
tf.Tensor(
[-0.19657845  0.44212212 -1.13071953 -1.23045254  0.55057123  1.01677005
 -0.38012885  0.60962063 -1.67847851 -0.25305115], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.05662659 -0.80185349 -1.60380021 -1.10114449 -0.40114725  0.54762343
 -1.74630306  2.36677379 -0.75058713 -0.67109365], shape=(10,), dtype=float64)
tf.Tensor(
[-1.05801191 -0.44241144  0.32520727  1.29261048 -0.30782782 -0.92391427
  0.14948935  0.59345372  0.88893776 -0.30576681], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.38763236 -0.95637417  1.05646857 -0.65538739 -0.24949638  1.24433852
  0.40862114  0.27250804 -1.54628978 -1.37900402], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.46040852  0.36889189  0.6091997  -0.34280094 -0.71138124 -0.13609663
  0.32633736 -0.99886188  1.47421087 -2.91628104], shape=(10,), dtype=float64)
tf.Tensor(
[-0.15838397  0.51308258  1.22451058  1.09374462  1.18459827  0.05779186
 -0.73929538 -1.39213397 -0.58540737 -0.07208634], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.89944959 -0.42390293  0.61530522  0.67920543  1.56440836  1.34096413
  0.37968904 -0.45895901 -1.38455114  0.03494874], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.4041736   0.34241922 -0.4385196  -0.0311751   1.55138529 -1.15289005
 -0.05523709 -0.93169502 -0.94331511  0.75232814], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.06804045 -1.29410246 -0.19339719 -0.56654768 -0.94885127 -0.80454834
 -0.84583886 -0.11236662 -0.13751504 -1.00020155], shape=(10,), dtype=float64)
tf.Tensor(
[-0.24522165  2.43590771  0.50921141  0.24554368 -2.44441172  0.88916235
  0.18320358  1.36780511 -2.23975045  0.8042535 ], shape=(10,), dtype=float64)
tf.Tensor(
[-0.65279726 -0.26995054 -0.86446779 -0.32053331 -0.47384696 -0.24389858
  2.18345709 -0.24965628 -0.89506696  1.4750929 ], shape=(10,), dtype=float64)
tf.Tensor(
[-0.99288955 -0.98924626 -0.60975313  0.06648027  0.30220054  1.55647281
 -1.11970285 -0.7552717   0.30309709 -0.78335239], shape=(10,), dtype=float64)
tf.Tensor(
[-0.46137369 -0.27045332 -0.39911858 -1.53724316  1.0538108  -0.06767822
 -0.48739181  0.61857942  1.11080521  0.36522243], shape=(10,), dtype=float64)
tf.Tensor(
[-0.81177494  0.10021773  1.22678075  1.18018295  0.37768532  0.12888707
  0.68143089  0.13280237 -0.69305348  0.64176132], shape=(10,), dtype=float64)
tf.Tensor(
[-0.85098162 -0.56914753 -1.56192697  0.40089277  0.62749834  0.59688479
 -1.04857112 -0.43609029 -0.34416012 -0.16328755], shape=(10,), dtype=float64)
tf.Tensor(
[-1.24898154 -1.51414541 -0.8994687  -0.67074531 -0.97463144 -0.34022657
  0.4730757  -0.09213546  0.02397735 -1.75607364], shape=(10,), dtype=float64)
tf.Tensor(
[-1.78761203 -0.11883798  1.31243987 -0.01840244 -0.69937985 -0.02942226
  0.87496921  0.11025765  0.52696419 -0.49222973], shape=(10,), dtype=float64)
tf.Tensor(
[-1.18480693 -0.15192414 -0.66761969 -0.01794246 -0.68829654 -0.25998341
 -0.42286735 -3.03880443  1.02423379 -1.70573631], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.55387173 -0.88579615 -0.85377783 -0.56099661 -0.07801495  0.52067029
  0.73550157  0.30825455 -0.22819644  0.10638198], shape=(10,), dtype=float64)
tf.Tensor(
[-0.82186843 -0.45030823  0.08106337 -0.26708248  0.05919531 -0.21202967
 -0.85190662  1.13059503 -1.51004413 -0.65260913], shape=(10,), dtype=float64)
tf.Tensor(
[-0.01019402  0.19262817 -0.09653374  0.30245189 -0.1411212  -0.20872114
 -0.24366352 -0.09874107 -1.22635691  0.7071221 ], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.17461314  2.18579395 -0.72096378  0.27594048 -0.50698252  1.62488943
  0.72827581  0.68885395 -0.27657751 -0.32259243], shape=(10,), dtype=float64)
tf.Tensor(
[-1.74077165 -0.09753145 -1.04052248 -0.82592425 -0.91872679 -1.59190478
  0.12144577 -0.50389244  1.07564252 -0.44700429], shape=(10,), dtype=float64)
tf.Tensor(
[ 2.21636488 -0.21331002  1.06265208  0.3880169  -0.2543586   1.42131514
  0.87254039 -0.23810739  0.11892428  0.16837715], shape=(10,), dtype=float64)
tf.Tensor(
[-0.98318169  1.12668547  1.06018419  0.10133    -0.82137184  0.56285655
 -0.59748291  1.15594191 -1.16236709  0.24342558], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.25382779  0.86562109 -1.3266608  -1.72858937 -1.35839299 -0.40181063
  1.40322813 -0.33174501 -1.01334694  1.18260998], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.13727106 -0.4719026   1.9941946   0.63280575 -1.21622355 -1.60903989
  2.4891089   1.50344786  1.13922673 -0.96345574], shape=(10,), dtype=float64)
tf.Tensor(
[-0.58701518  0.5194128  -1.75814356 -2.2079343   0.20039066  0.05051244
  0.09499009 -0.65202042 -0.01695042 -0.33867223], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.67045261 -1.12580275  2.02503602 -0.46571411  1.56938039  0.79700728
 -0.86092712 -1.5760726  -0.36194573 -0.54650306], shape=(10,), dtype=float64)
tf.Tensor(
[-1.17100745 -1.04923431  0.95568196 -0.63746015  0.01537479 -0.44421073
  1.00585602  1.81167283  2.23401298  0.67077382], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.62445302 -0.32075354  0.66020497 -0.70728813  0.82500033  0.90933964
  2.15313079  1.29858684 -0.26903357  1.47295966], shape=(10,), dtype=float64)
tf.Tensor(
[-0.37673464  0.34972518  0.4732094   0.871842   -1.12875381 -0.35533579
 -1.70016133 -0.45581821 -0.46603988 -1.65633858], shape=(10,), dtype=float64)
tf.Tensor(
[-0.61882254 -0.63950881  0.58632254 -0.68284987 -1.27361806  1.5811072
 -0.05718715  1.43202346 -0.76364127 -0.51657985], shape=(10,), dtype=float64)
tf.Tensor(
[-1.32420533 -0.65847988  0.71619771  0.88983566  0.16979319  0.74560078
 -0.45770206 -1.21247704  0.42531703 -0.23527907], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.91587007 -0.96038205  0.98273785 -0.90915436 -1.51696053  0.21562767
 -1.49663893  1.56194783 -0.10538618  1.63554209], shape=(10,), dtype=float64)
tf.Tensor(
[-0.57775861 -0.18172938 -0.14185929 -0.04366038 -0.35947076 -1.37627488
 -0.11655188 -0.24374647 -1.01470197 -1.0273865 ], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.47867169  1.30735593 -0.43374836  0.21807443  1.29130679 -1.03996615
  1.09215473 -0.18116972  0.18110023 -0.29441292], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.80145323  2.17012467 -0.37624137 -1.79432056 -0.38705061 -1.03949792
  0.13720759 -0.29018344  0.90441458 -1.14493271], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.04361667 -0.13709943  0.14685869 -1.41422111 -0.25523168  0.38014346
  1.86520416  0.03721562  1.49378809  0.07905378], shape=(10,), dtype=float64)
tf.Tensor(
[-0.41271862 -1.77600342 -1.06482561 -1.66003489  0.25136961  0.1335285
 -0.02289062 -0.45712895  2.40257208  0.68437039], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.77797923 -0.86284564 -0.31142328  0.37665964  0.56297673 -0.72194047
 -1.11233731 -0.02147794 -1.21429976 -0.37756731], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.34093152 -1.35205143  0.76955601 -0.08860505  1.63677878 -1.28089197
 -0.33244123 -0.758475    0.40863088  0.69430277], shape=(10,), dtype=float64)
tf.Tensor(
[-0.75292939 -2.52104115 -0.34679678 -0.59251933  1.07234692  0.35000293
  2.02097397 -0.28486688  0.98486314 -0.1831576 ], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.11340365  0.60147619 -0.60387035 -2.40535261  0.2063526  -0.43517115
 -0.28368717  0.57770616 -1.12913132  0.81475879], shape=(10,), dtype=float64)
tf.Tensor(
[-0.63301131 -0.79722187 -0.34915547  1.81350062 -0.95284456 -1.0169885
  2.82445378 -0.76974304 -0.95467535 -0.53345559], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.05190745 -0.24997126  0.39393562  0.04944116 -0.33354396 -0.91747955
  1.76728243  0.17651424  0.07508812  0.60534891], shape=(10,), dtype=float64)
tf.Tensor(
[-0.5922203  -0.85526296 -0.35836688 -0.05124687  0.57112191 -0.74611297
  0.67879685 -0.43833735 -1.17480898 -0.37447441], shape=(10,), dtype=float64)
tf.Tensor(
[-0.76930239 -0.71819723  0.24726599  1.28716223 -1.02714488  0.51076595
  1.24423832  2.91972501 -1.06834184  1.29679573], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.07017759  0.00233121 -0.73516578  0.54698036 -0.98648311 -1.02194086
 -0.16743573 -1.16938559 -0.03560017 -0.77352221], shape=(10,), dtype=float64)
tf.Tensor(
[-1.23943231 -0.68725004 -1.45591781  0.73018423 -0.69871509  0.49168835
 -1.16966672  1.87213404  0.51147222  1.0424952 ], shape=(10,), dtype=float64)
tf.Tensor(
[-0.73425711  1.78452655 -0.45386051  0.14856967  0.89083254 -0.82031832
  0.99509893  2.01706017 -0.91923542  1.16335062], shape=(10,), dtype=float64)
tf.Tensor(
[-0.63918142 -0.91394657 -1.47226196  0.52230188  1.08339832  0.83231263
  2.474444   -0.71171449 -0.13916621 -1.2800288 ], shape=(10,), dtype=float64)
tf.Tensor(
[-0.45541313 -2.52684377 -0.24090084  0.13536192 -0.58968623 -0.08000827
 -0.31173469 -0.45509087  0.10866132 -0.28232998], shape=(10,), dtype=float64)
tf.Tensor(
[-1.02005505 -1.41463385 -0.53396349 -0.53172943 -0.92431198  0.79653889
 -0.09034646  0.22072615 -0.93908825 -0.8836023 ], shape=(10,), dtype=float64)
tf.Tensor(
[ 1.82716955 -1.24432803 -0.6397197   0.57116165 -1.66208272  0.43354636
 -0.08035783  0.11797874 -0.00418168  1.01611772], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.84495199  0.85013849 -0.66790212  0.0781342   0.62807465 -0.81612923
  0.53880142 -0.03850802 -0.16468382 -0.7786689 ], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.95782075  0.61020393 -0.58316286 -0.8412154   1.07307595  0.40768989
  0.0511441   0.5288295  -0.05127404  0.3811116 ], shape=(10,), dtype=float64)
tf.Tensor(
[-0.57395228 -1.23315986  1.04617256 -0.68068233 -0.48637143  1.05888247
  0.68288853 -0.52827617  0.62352843  1.59312603], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.28912771 -0.7650718   0.48978487  0.19321484  0.56685789  0.963804
 -0.159725   -1.0673944  -0.60684301 -0.09402856], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.5748224  -0.25795728 -0.91282032 -1.06322045  0.6777146  -0.64555125
 -0.47966045 -0.90072142 -0.25982346  1.28675534], shape=(10,), dtype=float64)
tf.Tensor(
[-0.90709825 -1.96733841  0.24701291 -0.52955215  0.52747082 -0.46583218
 -0.57126402  0.80646827  2.01533379 -1.6349534 ], shape=(10,), dtype=float64)
tf.Tensor(
[-0.33398036  0.0422988  -1.25514516  0.9527448   0.12996866  2.3764368
 -0.6100736   0.54777122  0.62956792  0.45154481], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.70614892 -0.78152964 -1.181331    2.05396828  0.60867535  1.43224263
 -0.13947172  0.38026456 -0.91320284 -0.21757654], shape=(10,), dtype=float64)
tf.Tensor(
[ 2.57071287  1.09260453  0.06613767 -0.39726169 -0.44112903 -1.16838413
 -0.4047787   1.27960848 -1.16928946  0.70258802], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.35298814  1.20518879 -1.29545753  0.87796008 -1.10121678  0.65353961
 -1.03988266 -0.06621752 -0.87846105 -1.52730398], shape=(10,), dtype=float64)
tf.Tensor(
[ 0.87237407 -0.49521749  0.01656668 -0.61612859  0.8372091   1.66467886
  1.64331292 -0.27261248 -1.99450312 -0.32452505], shape=(10,), dtype=float64)
tf.Tensor(
[-0.16188547  0.07431607 -2.07402497 -0.6786773  -0.31496177 -2.78819724
 -0.23673091  0.68463587 -1.01306664 -0.74763498], shape=(10,), dtype=float64)
tf.Tensor(
[-0.17947371  1.94492052  1.89891316  0.44524908 -0.31991595  0.0596293
 -1.41225997 -2.3957878   0.20677488  0.20551751], shape=(10,), dtype=float64)
tf.Tensor(
[-0.16324935 -1.18911605 -0.63858733 -0.48961623  1.04963035 -0.57604245

In [72]:
x.shape

TensorShape([64, 10])

In [74]:
z = tf.reshape(x, (640, -1))

In [82]:
model.train_function

In [105]:
y.shape

TensorShape([20])

In [116]:
x = tf.transpose(x)

In [120]:
y = tf.random.normal((10,1))
y.shape

TensorShape([10, 1])

In [121]:
with tf.GradientTape() as tape:
    pred = model(x, training=True)
    loss = loss_fn(y, pred)
    grads = tape.gradient(loss, model.trainable_variables)

In [96]:
model

In [122]:
grads

[<tf.Tensor: shape=(20, 64), dtype=float32, numpy=
 array([[ 0.02572737,  0.07310952,  0.03541078, ...,  0.08403654,
          0.02415946, -0.05523389],
        [ 0.02454175, -0.11924741,  0.05034967, ...,  0.01178224,
         -0.12622604, -0.01152351],
        [ 0.01217393, -0.1114243 ,  0.01451463, ..., -0.07921324,
         -0.18295002, -0.05697665],
        ...,
        [ 0.01042527,  0.03907387, -0.01292396, ..., -0.00498579,
          0.062736  ,  0.01116171],
        [-0.01912504,  0.00699851, -0.01368154, ..., -0.02055784,
          0.02397827, -0.01025016],
        [-0.0376459 ,  0.01122632, -0.01664925, ...,  0.01242814,
          0.04888831,  0.00205421]], shape=(20, 64), dtype=float32)>,
 <tf.Tensor: shape=(64,), dtype=float32, numpy=
 array([ 1.20718069e-02, -1.34245336e-01,  5.91536090e-02, -6.62488211e-03,
         1.31622851e-02, -3.00574973e-02, -8.70307349e-03,  4.86528128e-02,
         4.50487249e-03,  2.90465429e-02,  2.98116989e-02,  3.54481419e-03,
         3.21908146e-02,  2.79948786e-02, -2.96035092e-02,  2.66093791e-01,
        -1.43912315e-01, -7.16304965e-03,  4.95752692e-03,  1.08633280e-01,
        -7.86401033e-02,  1.37129053e-01, -5.79807442e-03,  1.90138686e-02,
        -2.27038050e-04,  2.48345509e-02, -2.64652185e-02, -9.67545956e-02,
        -1.59235317e-02, -1.48710027e-01, -3.90275605e-02, -1.58001781e-02,
        -4.91885766e-02,  1.61734521e-02, -2.32334696e-02, -1.05700314e-01,
         1.01036280e-02, -1.74372301e-01,  5.59655577e-02, -4.37910929e-02,
         4.52060718e-03, -6.86197914e-03, -5.23499772e-02,  1.23667039e-01,
         5.91344163e-02,  7.23530203e-02, -2.58263350e-02,  1.34869828e-03,
         3.17870975e-02, -7.30508491e-02,  3.72014358e-04,  2.96326466e-02,
        -1.02271549e-02,  6.08799187e-03,  4.83043790e-02, -8.78712069e-03,
         2.71541849e-02,  5.74707538e-02,  1.58886984e-03,  9.36812628e-03,
         4.84768339e-02, -3.01297158e-02, -1.33761108e-01,  6.25337148e-03],
       dtype=float32)>,
 <tf.Tensor: shape=(64, 1), dtype=float32, numpy=
 array([[-0.06240762],
        [ 0.35458028],
        [ 0.13378079],
        [-0.01863012],
        [ 0.03408   ],
        [ 0.1470396 ],
        [-0.04061152],
        [ 0.21557155],
        [-0.00540309],
        [-0.11685573],
        [ 0.01498693],
        [ 0.0011564 ],
        [ 0.06691815],
        [ 0.17555887],
        [ 0.14732029],
        [ 0.4459121 ],
        [ 0.49164826],
        [ 0.07205139],
        [ 0.03889461],
        [ 0.5113969 ],
        [ 0.09777156],
        [ 0.41128975],
        [-0.01510909],
        [-0.18246624],
        [ 0.05807158],
        [ 0.32612312],
        [ 0.4560766 ],
        [ 0.5012078 ],
        [-0.05477836],
        [ 0.15599272],
        [ 0.1237651 ],
        [ 0.09565827],
        [ 0.12010763],
        [ 0.07083234],
        [ 0.08262514],
        [ 0.0966192 ],
        [ 0.11563965],
        [ 0.5659379 ],
        [ 0.13505025],
        [ 0.424381  ],
        [ 0.04118226],
        [ 0.24987197],
        [ 0.2700254 ],
        [ 0.46640253],
        [ 0.03860216],
        [ 0.09859014],
        [ 0.3178898 ],
        [ 0.18280445],
        [ 0.01127394],
        [ 0.3645781 ],
        [ 0.00930139],
        [-0.02698377],
        [ 0.06803916],
        [ 0.07136304],
        [-0.06989356],
        [ 0.07231466],
        [ 0.12448609],
        [-0.17359073],
        [ 0.04559669],
        [ 0.31594053],
        [ 0.23034565],
        [ 0.13859569],
        [ 0.08263142],
        [-0.02768913]], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.5775806], dtype=float32)>]

In [123]:
# 1. Global gradient norm
global_norm = tf.linalg.global_norm(grads)

In [125]:
# 2. Clip to global norm 1.0
clipped_grads, z = tf.clip_by_global_norm(grads, 1.0)

In [128]:
clipped_grads

[<tf.Tensor: shape=(20, 64), dtype=float32, numpy=
 array([[ 0.00825948,  0.02347098,  0.01136823, ...,  0.02697898,
          0.00775612, -0.01773221],
        [ 0.00787885, -0.03828302,  0.01616419, ...,  0.00378256,
         -0.04052344, -0.00369949],
        [ 0.0039083 , -0.03577151,  0.00465976, ..., -0.02543051,
         -0.05873403, -0.01829171],
        ...,
        [ 0.00334691,  0.01254422, -0.00414909, ..., -0.00160063,
          0.02014068,  0.00358334],
        [-0.00613987,  0.00224679, -0.0043923 , ..., -0.00659986,
          0.00769795, -0.0032907 ],
        [-0.01208579,  0.00360408, -0.00534505, ...,  0.00398991,
          0.01569504,  0.00065948]], shape=(20, 64), dtype=float32)>,
 <tf.Tensor: shape=(64,), dtype=float32, numpy=
 array([ 3.8755164e-03, -4.3097939e-02,  1.8990593e-02, -2.1268432e-03,
         4.2256019e-03, -9.6496176e-03, -2.7940229e-03,  1.5619433e-02,
         1.4462381e-03,  9.3250629e-03,  9.5707066e-03,  1.1380223e-03,
         1.0334495e-02,  8.9874379e-03, -9.5038703e-03,  8.5426390e-02,
        -4.6201412e-02, -2.2996156e-03,  1.5915576e-03,  3.4875479e-02,
        -2.5246512e-02,  4.4023722e-02, -1.8614059e-03,  6.1041862e-03,
        -7.2887982e-05,  7.9728505e-03, -8.4963571e-03, -3.1061962e-02,
        -5.1120687e-03, -4.7741663e-02, -1.2529355e-02, -5.0724675e-03,
        -1.5791433e-02,  5.1923031e-03, -7.4588414e-03, -3.3933885e-02,
         3.2436550e-03, -5.5980247e-02,  1.7967107e-02, -1.4058633e-02,
         1.4512895e-03, -2.2029604e-03, -1.6806366e-02,  3.9701898e-02,
         1.8984431e-02,  2.3228114e-02, -8.2912510e-03,  4.3298426e-04,
         1.0204886e-02, -2.3452144e-02,  1.1943098e-04,  9.5132245e-03,
        -3.2833118e-03,  1.9544805e-03,  1.5507571e-02, -2.8210052e-03,
         8.7175425e-03,  1.8450333e-02,  5.1008858e-04,  3.0075305e-03,
         1.5562937e-02, -9.6728029e-03, -4.2942483e-02,  2.0075738e-03],
       dtype=float32)>,
 <tf.Tensor: shape=(64, 1), dtype=float32, numpy=
 array([[-0.02003526],
        [ 0.11383397],
        [ 0.0429488 ],
        [-0.00598099],
        [ 0.010941  ],
        [ 0.0472054 ],
        [-0.01303787],
        [ 0.0692068 ],
        [-0.0017346 ],
        [-0.0375152 ],
        [ 0.00481138],
        [ 0.00037125],
        [ 0.02148331],
        [ 0.05636118],
        [ 0.0472955 ],
        [ 0.14315501],
        [ 0.15783809],
        [ 0.02313128],
        [ 0.01248667],
        [ 0.16417816],
        [ 0.03138845],
        [ 0.1320399 ],
        [-0.0048506 ],
        [-0.05857871],
        [ 0.01864322],
        [ 0.10469812],
        [ 0.1464182 ],
        [ 0.16090707],
        [-0.01758597],
        [ 0.05007969],
        [ 0.03973338],
        [ 0.03071   ],
        [ 0.03855919],
        [ 0.02273992],
        [ 0.02652586],
        [ 0.0310185 ],
        [ 0.03712479],
        [ 0.18168792],
        [ 0.04335635],
        [ 0.13624269],
        [ 0.0132211 ],
        [ 0.08021855],
        [ 0.08668859],
        [ 0.14973323],
        [ 0.01239278],
        [ 0.03165124],
        [ 0.10205491],
        [ 0.05868729],
        [ 0.00361937],
        [ 0.11704365],
        [ 0.00298611],
        [-0.00866283],
        [ 0.0218432 ],
        [ 0.02291029],
        [-0.02243853],
        [ 0.0232158 ],
        [ 0.03996484],
        [-0.05572933],
        [ 0.0146383 ],
        [ 0.10142911],
        [ 0.07394985],
        [ 0.04449457],
        [ 0.02652788],
        [-0.00888928]], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.18542568], dtype=float32)>]

In [136]:

grads[0].shape

TensorShape([20, 64])

In [135]:
len(grads)

4

In [138]:
X_train_np.shape, y_train_np.shape

((20, 10), (20,))

In [140]:
train_ds = tf.data.Dataset.from_tensor_slices((X_train_np, y_train_np)).shuffle(5000).batch(64).prefetch(tf.data.AUTOTUNE)

In [141]:
len(train_ds)

1

In [143]:
import pandas as pd

In [144]:
df = pd.DataFrame(columns = ['age', 'churn'])

In [145]:
df['age'] = np.arange(30, 45)

In [146]:
df['churn'] = np.random.randint(0, 2, 15)

In [148]:
X = df.drop(columns=["churn"])
y = df["churn"]

In [155]:
from sklearn.model_selection import train_test_split

In [156]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, train_size=0.7, random_state=42, shuffle=True, stratify=y)

In [158]:
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, shuffle=True, stratify=y_temp)

In [167]:
X_train.loc[0, 'age'] = np.nan

In [168]:
# Using only X_train, write code to:

# compute median age
# add age_missing
# fill missing age
# fill missing country with "Unknown"

median_age = X_train['age'].median()
X_train['age_missing'] = X_train['age'].fillna(0).astype(bool)
X_train['age'].fillna(median_age, inplace=True)
X_train['country'].fillna('Unknown')

In [169]:
X_train

     age  age_missing
2   32.0         True
1   31.0         True
6   36.0         True
9   39.0         True
10  40.0         True
13  43.0         True
0    NaN        False
12  42.0         True
4   34.0         True
8   38.0         True

In [171]:
from sklearn.preprocessing import StandardScaler

In [172]:
scaler = StandardScaler()

In [179]:
X_train['age'] = X_train['age'].fillna(median_age)

In [180]:
scaler.fit_transform(X_train[['age']])

array([[-1.38659861],
       [-1.64822099],
       [-0.34010909],
       [ 0.44475805],
       [ 0.70638043],
       [ 1.49124757],
       [ 0.18313567],
       [ 1.22962519],
       [-0.86335385],
       [ 0.18313567]])

In [181]:
scaler.transform(X_val[['age']])

array([[-1.12497623],
       [ 0.96800281]])

In [182]:
from sklearn.preprocessing import OneHotEncoder

In [183]:
OneHotEncoder?

Init signature:
OneHotEncoder(
    *,
    categories='auto',
    drop=None,
    sparse_output=True,
    dtype=<class 'numpy.float64'>,
    handle_unknown='error',
    min_frequency=None,
    max_categories=None,
    feature_name_combiner='concat',
)
Docstring:
Encode categorical features as a one-hot numeric array.

The input to this transformer should be an array-like of integers or
strings, denoting the values taken on by categorical (discrete) features.
The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
encoding scheme. This creates a binary column for each category and
returns a sparse matrix or dense array (depending on the ``sparse_output``
parameter).

By default, the encoder derives the categories based on the unique values
in each feature. Alternatively, you can also specify the `categories`
manually.

This encoding is needed for feeding categorical data to many scikit-learn
estimators, notably linear models and SVMs with the standard kernels.

Note: a one-hot encoding of y labels should use a LabelBinarizer
instead.

Read more in the :ref:`User Guide <preprocessing_categorical_features>`.
For a comparison of different encoders, refer to:
:ref:`sphx_glr_auto_examples_preprocessing_plot_target_encoder.py`.

Parameters
----------
categories : 'auto' or a list of array-like, default='auto'
    Categories (unique values) per feature:

    - 'auto' : Determine categories automatically from the training data.
    - list : ``categories[i]`` holds the categories expected in the ith
      column. The passed categories should not mix strings and numeric
      values within a single feature, and should be sorted in case of
      numeric values.

    The used categories can be found in the ``categories_`` attribute.

    .. versionadded:: 0.20

drop : {'first', 'if_binary'} or an array-like of shape (n_features,),             default=None
    Specifies a methodology to use to drop one of the categories per
    feature. This is useful in situations where perfectly collinear
    features cause problems, such as when feeding the resulting data
    into an unregularized linear regression model.

    However, dropping one category breaks the symmetry of the original
    representation and can therefore induce a bias in downstream models,
    for instance for penalized linear classification or regression models.

    - None : retain all features (the default).
    - 'first' : drop the first category in each feature. If only one
      category is present, the feature will be dropped entirely.
    - 'if_binary' : drop the first category in each feature with two
      categories. Features with 1 or more than 2 categories are
      left intact.
    - array : ``drop[i]`` is the category in feature ``X[:, i]`` that
      should be dropped.

    When `max_categories` or `min_frequency` is configured to group
    infrequent categories, the dropping behavior is handled after the
    grouping.

    .. versionadded:: 0.21
       The parameter `drop` was added in 0.21.

    .. versionchanged:: 0.23
       The option `drop='if_binary'` was added in 0.23.

    .. versionchanged:: 1.1
        Support for dropping infrequent categories.

sparse_output : bool, default=True
    When ``True``, it returns a SciPy sparse matrix/array
    in "Compressed Sparse Row" (CSR) format.

    .. versionadded:: 1.2
       `sparse` was renamed to `sparse_output`

dtype : number type, default=np.float64
    Desired dtype of output.

handle_unknown : {'error', 'ignore', 'infrequent_if_exist', 'warn'},                      default='error'
    Specifies the way unknown categories are handled during :meth:`transform`.

    - 'error' : Raise an error if an unknown category is present during transform.
    - 'ignore' : When an unknown category is encountered during
      transform, the resulting one-hot encoded columns for this feature
      will be all zeros. In the inverse transform, an unknown category
      will be denoted as None.
    - 'infrequent_if_exist' : When an unknown category is encountered
      during transform, the resulting one-hot encoded columns for this
      feature will map to the infrequent category if it exists. The
      infrequent category will be mapped to the last position in the
      encoding. During inverse transform, an unknown category will be
      mapped to the category denoted `'infrequent'` if it exists. If the
      `'infrequent'` category does not exist, then :meth:`transform` and
      :meth:`inverse_transform` will handle an unknown category as with
      `handle_unknown='ignore'`. Infrequent categories exist based on
      `min_frequency` and `max_categories`. Read more in the
      :ref:`User Guide <encoder_infrequent_categories>`.
    - 'warn' : When an unknown category is encountered during transform
      a warning is issued, and the encoding then proceeds as described for
      `handle_unknown="infrequent_if_exist"`.

    .. versionchanged:: 1.1
        `'infrequent_if_exist'` was added to automatically handle unknown
        categories and infrequent categories.

    .. versionadded:: 1.6
       The option `"warn"` was added in 1.6.

min_frequency : int or float, default=None
    Specifies the minimum frequency below which a category will be
    considered infrequent.

    - If `int`, categories with a smaller cardinality will be considered
      infrequent.

    - If `float`, categories with a smaller cardinality than
      `min_frequency * n_samples`  will be considered infrequent.

    .. versionadded:: 1.1
        Read more in the :ref:`User Guide <encoder_infrequent_categories>`.

max_categories : int, default=None
    Specifies an upper limit to the number of output features for each input
    feature when considering infrequent categories. If there are infrequent
    categories, `max_categories` includes the category representing the
    infrequent categories along with the frequent categories. If `None`,
    there is no limit to the number of output features.

    .. versionadded:: 1.1
        Read more in the :ref:`User Guide <encoder_infrequent_categories>`.

feature_name_combiner : "concat" or callable, default="concat"
    Callable with signature `def callable(input_feature, category)` that returns a
    string. This is used to create feature names to be returned by
    :meth:`get_feature_names_out`.

    `"concat"` concatenates encoded feature name and category with
    `feature + "_" + str(category)`.E.g. feature X with values 1, 6, 7 create
    feature names `X_1, X_6, X_7`.

    .. versionadded:: 1.3

Attributes
----------
categories_ : list of arrays
    The categories of each feature determined during fitting
    (in order of the features in X and corresponding with the output
    of ``transform``). This includes the category specified in ``drop``
    (if any).

drop_idx_ : array of shape (n_features,)
    - ``drop_idx_[i]`` is the index in ``categories_[i]`` of the category
      to be dropped for each feature.
    - ``drop_idx_[i] = None`` if no category is to be dropped from the
      feature with index ``i``, e.g. when `drop='if_binary'` and the
      feature isn't binary.
    - ``drop_idx_ = None`` if all the transformed features will be
      retained.

    If infrequent categories are enabled by setting `min_frequency` or
    `max_categories` to a non-default value and `drop_idx[i]` corresponds
    to an infrequent category, then the entire infrequent category is
    dropped.

    .. versionchanged:: 0.23
       Added the possibility to contain `None` values.

infrequent_categories_ : list of ndarray
    Defined only if infrequent categories are enabled by setting
    `min_frequency` or `max_categories` to a non-default value.
    `infrequent_categories_[i]` are the infrequent categories for feature
    `i`. If the feature `i` has no infrequent categories
    `infrequent_categories_[i]` is None.

    .. versionadded:: 1.1

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 1.0

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

feature_name_combiner : callable or None
    Callable with signature `def callable(input_feature, category)` that returns a
    string. This is used to create feature names to be returned by
    :meth:`get_feature_names_out`.

    .. versionadded:: 1.3

See Also
--------
OrdinalEncoder : Performs an ordinal (integer)
  encoding of the categorical features.
TargetEncoder : Encodes categorical features using the target.
sklearn.feature_extraction.DictVectorizer : Performs a one-hot encoding of
  dictionary items (also handles string-valued features).
sklearn.feature_extraction.FeatureHasher : Performs an approximate one-hot
  encoding of dictionary items or strings.
LabelBinarizer : Binarizes labels in a one-vs-all
  fashion.
MultiLabelBinarizer : Transforms between iterable of
  iterables and a multilabel format, e.g. a (samples x classes) binary
  matrix indicating the presence of a class label.

Examples
--------
Given a dataset with two features, we let the encoder find the unique
values per feature and transform the data to a binary one-hot encoding.

>>> from sklearn.preprocessing import OneHotEncoder

One can discard categories not seen during `fit`:

>>> enc = OneHotEncoder(handle_unknown='ignore')
>>> X = [['Male', 1], ['Female', 3], ['Female', 2]]
>>> enc.fit(X)
OneHotEncoder(handle_unknown='ignore')
>>> enc.categories_
[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
>>> enc.transform([['Female', 1], ['Male', 4]]).toarray()
array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])
>>> enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])
array([['Male', 1],
       [None, 2]], dtype=object)
>>> enc.get_feature_names_out(['gender', 'group'])
array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'], ...)

One can always drop the first column for each feature:

>>> drop_enc = OneHotEncoder(drop='first').fit(X)
>>> drop_enc.categories_
[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
>>> drop_enc.transform([['Female', 1], ['Male', 2]]).toarray()
array([[0., 0., 0.],
       [1., 1., 0.]])

Or drop a column for feature only having 2 categories:

>>> drop_binary_enc = OneHotEncoder(drop='if_binary').fit(X)
>>> drop_binary_enc.transform([['Female', 1], ['Male', 2]]).toarray()
array([[0., 1., 0., 0.],
       [1., 0., 1., 0.]])

One can change the way feature names are created.

>>> def custom_combiner(feature, category):
...     return str(feature) + "_" + type(category).__name__ + "_" + str(category)
>>> custom_fnames_enc = OneHotEncoder(feature_name_combiner=custom_combiner).fit(X)
>>> custom_fnames_enc.get_feature_names_out()
array(['x0_str_Female', 'x0_str_Male', 'x1_int_1', 'x1_int_2', 'x1_int_3'],
      dtype=object)

Infrequent categories are enabled by setting `max_categories` or `min_frequency`.

>>> import numpy as np
>>> X = np.array([["a"] * 5 + ["b"] * 20 + ["c"] * 10 + ["d"] * 3], dtype=object).T
>>> ohe = OneHotEncoder(max_categories=3, sparse_output=False).fit(X)
>>> ohe.infrequent_categories_
[array(['a', 'd'], dtype=object)]
>>> ohe.transform([["a"], ["b"]])
array([[0., 0., 1.],
       [1., 0., 0.]])
File:           ~/Library/Caches/pypoetry/virtualenvs/transformers-from-first-principles-ROJJTl4v-py3.12/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py
Type:           type
Subclasses:

In [188]:
countries = ['France', 'Morocco', 'UAE']
X_train['country'] = np.random.choice(countries, len(X_train))

In [189]:
X_val['country'] = np.random.choice(countries, len(X_val))

In [192]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit_transform(X_train[['country']])
enc.fit_transform(X_val[['country']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (2, 1)>

In [193]:
X_train#['country']

     age  age_missing  country
2   32.0         True      UAE
1   31.0         True      UAE
6   36.0         True   France
9   39.0         True   France
10  40.0         True  Morocco
13  43.0         True      UAE
0   38.0        False   France
12  42.0         True  Morocco
4   34.0         True   France
8   38.0         True   France

In [194]:
X_val

    age country
3    33     UAE
11   41     UAE

In [195]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')

X_train_country = enc.fit_transform(X_train[['country']])
X_val_country = enc.transform(X_val[['country']])

In [201]:
type(X_val_country)

scipy.sparse._csr.csr_matrix

In [202]:
from scipy.sparse import hstack

X_train_country = enc.fit_transform(X_train[['country']])
X_val_country = enc.transform(X_val[['country']])

X_train_num = X_train[['age', ]].values
X_val_num = X_val[['age']].values

X_train_final = hstack([X_train_num, X_train_country])
X_val_final = hstack([X_val_num, X_val_country])

In [203]:
X_train_final

<COOrdinate sparse matrix of dtype 'float64'
	with 20 stored elements and shape (10, 4)>

In [204]:
print(X_train_final.toarray())

[[32.  0.  0.  1.]
 [31.  0.  0.  1.]
 [36.  1.  0.  0.]
 [39.  1.  0.  0.]
 [40.  0.  1.  0.]
 [43.  0.  0.  1.]
 [38.  1.  0.  0.]
 [42.  0.  1.  0.]
 [34.  1.  0.  0.]
 [38.  1.  0.  0.]]

In [205]:
print(X_train_final)

<COOrdinate sparse matrix of dtype 'float64'
	with 20 stored elements and shape (10, 4)>
  Coords	Values
  (0, 0)	32.0
  (1, 0)	31.0
  (2, 0)	36.0
  (3, 0)	39.0
  (4, 0)	40.0
  (5, 0)	43.0
  (6, 0)	38.0
  (7, 0)	42.0
  (8, 0)	34.0
  (9, 0)	38.0
  (0, 3)	1.0
  (1, 3)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 2)	1.0
  (5, 3)	1.0
  (6, 1)	1.0
  (7, 2)	1.0
  (8, 1)	1.0
  (9, 1)	1.0

In [206]:
X_train_np = X_train_final.toarray()
type(X_train_final.toarray())

numpy.ndarray

In [209]:
y_train_np = y_train.values
type(y_train.values)

numpy.ndarray

In [210]:
train_ds = tf.data.Dataset.from_tensor_slices((X_train_np, y_train_np)).shuffle(5000).batch(64).prefetch(tf.data.AUTOTUNE)

In [216]:
# Block 4 retest — Question 8

# Build a Keras binary classifier with:

# input dimension 12
# hidden layers 32 and 16
# ReLU
# dropout 0.2
# one raw output logit

model = tf.keras.Sequential([tf.keras.Input((4,)),
                             tf.keras.layers.Dense(32, activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(16, activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(1),
                            ])

In [217]:
loss_fn = tf.keras.losses.BinaryCrossentropy(from_logits=True)
optim = tf.keras.optimizers.Adam(learning_rate=1e-3)

In [ ]:
with tf.GradientTape() as tape:
    pred = model(x, training=True)
    loss = loss_fn(y, pred)

grads = tape.gradient(loss, model.trainable_variables)
optimizer.apply_gradients(zip(grads, model.trainable_variables))

loss_metric.update_state(loss)

In [215]:
x.shape

TensorShape([10, 4])

In [218]:
loss_metric = tf.keras.metrics.Mean(name="loss")
for x, y in train_ds:
    with tf.GradientTape() as tape:
        pred = model(x, training=True)
        loss = loss_fn(y, pred)

    grads = tape.gradient(loss, model.trainable_variables)
    optim.apply_gradients(zip(grads, model.trainable_variables))

    loss_metric.update_state(loss)
print("loss:", loss_metric.result().numpy())

loss: 5.4672394

In [219]:
pred.shape

TensorShape([10, 1])

In [221]:
probs = tf.sigmoid(pred)

In [222]:
probs

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.9963967 ],
       [0.9999996 ],
       [0.9994534 ],
       [0.9990057 ],
       [0.9999999 ],
       [0.99997926],
       [0.75744855],
       [0.9993508 ],
       [1.        ],
       [0.9999079 ]], dtype=float32)>

In [225]:

probs = tf.sigmoid(pred)
class_pred = tf.cast(probs > 0.3, tf.int32)

In [226]:
class_pred

<tf.Tensor: shape=(10, 1), dtype=int32, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int32)>